apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: sage007/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - containerPort: 7111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7111
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7111
          initialDelaySeconds: 5
          periodSeconds: 10
