namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP 

image:
  repository: sage007/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

resources:
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  path: /metrics

readinessProbe:
  path: /healthz
